plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/home/rosssaunders/code/rosssaunders/openferric/www"
publishOrigin = "config"
commandOrigin = "config"
command = "    curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh && rustup target add wasm32-unknown-unknown && wasm-pack build wasm --target web --out-dir ../www/pkg\n  "

[build.environment]
RUSTUP_TOOLCHAIN = "1.94.0"
CARGO_TERM_COLOR = "always"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]