[build]
  command = """
    curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh && \
    rustup target add wasm32-unknown-unknown && \
    wasm-pack build openferric-wasm --target web --out-dir ../www/pkg
  """
  publish = "www"

[build.environment]
  RUSTUP_TOOLCHAIN = "1.94.0"
  CARGO_TERM_COLOR = "always"
