//! QuantLib Reference Tests
//!
//! Validates OpenFerric pricing engines against reference values from:
//! 1. Haug, "Option Pricing Formulas" (McGraw-Hill 1998) — European & Barrier options
//! 2. Alan Lewis, Wilmott.com — Heston model reference prices (12-digit precision)
//! 3. QuantLib cached regression values — Heston model
//!
//! All test vectors extracted directly from QuantLib C++ test-suite source files.

use openferric::core::{BarrierDirection, BarrierStyle, OptionType, PricingEngine};
use openferric::engines::analytic::{BarrierAnalyticEngine, BlackScholesEngine};
use openferric::engines::fft::heston_price_fft;
use openferric::instruments::{BarrierOption, VanillaOption};
use openferric::market::Market;

// ============================================================================
// European Black-Scholes options
// Source: QuantLib test-suite/europeanoption.cpp lines 288-332
// Reference: Haug, "Option Pricing Formulas", McGraw-Hill 1998
// ============================================================================

struct EuropeanCase {
    option_type: OptionType,
    strike: f64,
    spot: f64,
    dividend: f64,
    rate: f64,
    expiry: f64,
    vol: f64,
    expected: f64,
    tolerance: f64,
}

fn european_haug_cases() -> Vec<EuropeanCase> {
    vec![
        // pag 2-8
        EuropeanCase {
            option_type: OptionType::Call,
            strike: 65.00,
            spot: 60.00,
            dividend: 0.00,
            rate: 0.08,
            expiry: 0.25,
            vol: 0.30,
            expected: 2.1334,
            tolerance: 1.0e-4,
        },
        EuropeanCase {
            option_type: OptionType::Put,
            strike: 95.00,
            spot: 100.00,
            dividend: 0.05,
            rate: 0.10,
            expiry: 0.50,
            vol: 0.20,
            expected: 2.4648,
            tolerance: 1.0e-4,
        },
        EuropeanCase {
            option_type: OptionType::Put,
            strike: 19.00,
            spot: 19.00,
            dividend: 0.10,
            rate: 0.10,
            expiry: 0.75,
            vol: 0.28,
            expected: 1.7011,
            tolerance: 1.0e-4,
        },
        EuropeanCase {
            option_type: OptionType::Call,
            strike: 19.00,
            spot: 19.00,
            dividend: 0.10,
            rate: 0.10,
            expiry: 0.75,
            vol: 0.28,
            expected: 1.7011,
            tolerance: 1.0e-4,
        },
        EuropeanCase {
            option_type: OptionType::Call,
            strike: 1.60,
            spot: 1.56,
            dividend: 0.08,
            rate: 0.06,
            expiry: 0.50,
            vol: 0.12,
            expected: 0.0291,
            tolerance: 1.0e-4,
        },
        EuropeanCase {
            option_type: OptionType::Put,
            strike: 70.00,
            spot: 75.00,
            dividend: 0.05,
            rate: 0.10,
            expiry: 0.50,
            vol: 0.35,
            expected: 4.0870,
            tolerance: 1.0e-4,
        },
        // pag 24 — Calls
        EuropeanCase {
            option_type: OptionType::Call,
            strike: 100.00,
            spot: 90.00,
            dividend: 0.10,
            rate: 0.10,
            expiry: 0.10,
            vol: 0.15,
            expected: 0.0205,
            tolerance: 1.0e-4,
        },
        EuropeanCase {
            option_type: OptionType::Call,
            strike: 100.00,
            spot: 100.00,
            dividend: 0.10,
            rate: 0.10,
            expiry: 0.10,
            vol: 0.15,
            expected: 1.8734,
            tolerance: 1.0e-4,
        },
        EuropeanCase {
            option_type: OptionType::Call,
            strike: 100.00,
            spot: 110.00,
            dividend: 0.10,
            rate: 0.10,
            expiry: 0.10,
            vol: 0.15,
            expected: 9.9413,
            tolerance: 1.0e-4,
        },
        EuropeanCase {
            option_type: OptionType::Call,
            strike: 100.00,
            spot: 90.00,
            dividend: 0.10,
            rate: 0.10,
            expiry: 0.10,
            vol: 0.25,
            expected: 0.3150,
            tolerance: 1.0e-4,
        },
        EuropeanCase {
            option_type: OptionType::Call,
            strike: 100.00,
            spot: 100.00,
            dividend: 0.10,
            rate: 0.10,
            expiry: 0.10,
            vol: 0.25,
            expected: 3.1217,
            tolerance: 1.0e-4,
        },
        EuropeanCase {
            option_type: OptionType::Call,
            strike: 100.00,
            spot: 110.00,
            dividend: 0.10,
            rate: 0.10,
            expiry: 0.10,
            vol: 0.25,
            expected: 10.3556,
            tolerance: 1.0e-4,
        },
        EuropeanCase {
            option_type: OptionType::Call,
            strike: 100.00,
            spot: 90.00,
            dividend: 0.10,
            rate: 0.10,
            expiry: 0.10,
            vol: 0.35,
            expected: 0.9474,
            tolerance: 1.0e-4,
        },
        EuropeanCase {
            option_type: OptionType::Call,
            strike: 100.00,
            spot: 100.00,
            dividend: 0.10,
            rate: 0.10,
            expiry: 0.10,
            vol: 0.35,
            expected: 4.3693,
            tolerance: 1.0e-4,
        },
        EuropeanCase {
            option_type: OptionType::Call,
            strike: 100.00,
            spot: 110.00,
            dividend: 0.10,
            rate: 0.10,
            expiry: 0.10,
            vol: 0.35,
            expected: 11.1381,
            tolerance: 1.0e-4,
        },
        EuropeanCase {
            option_type: OptionType::Call,
            strike: 100.00,
            spot: 90.00,
            dividend: 0.10,
            rate: 0.10,
            expiry: 0.50,
            vol: 0.15,
            expected: 0.8069,
            tolerance: 1.0e-4,
        },
        EuropeanCase {
            option_type: OptionType::Call,
            strike: 100.00,
            spot: 100.00,
            dividend: 0.10,
            rate: 0.10,
            expiry: 0.50,
            vol: 0.15,
            expected: 4.0232,
            tolerance: 1.0e-4,
        },
        EuropeanCase {
            option_type: OptionType::Call,
            strike: 100.00,
            spot: 110.00,
            dividend: 0.10,
            rate: 0.10,
            expiry: 0.50,
            vol: 0.15,
            expected: 10.5769,
            tolerance: 1.0e-4,
        },
        EuropeanCase {
            option_type: OptionType::Call,
            strike: 100.00,
            spot: 90.00,
            dividend: 0.10,
            rate: 0.10,
            expiry: 0.50,
            vol: 0.25,
            expected: 2.7026,
            tolerance: 1.0e-4,
        },
        EuropeanCase {
            option_type: OptionType::Call,
            strike: 100.00,
            spot: 100.00,
            dividend: 0.10,
            rate: 0.10,
            expiry: 0.50,
            vol: 0.25,
            expected: 6.6997,
            tolerance: 1.0e-4,
        },
        EuropeanCase {
            option_type: OptionType::Call,
            strike: 100.00,
            spot: 110.00,
            dividend: 0.10,
            rate: 0.10,
            expiry: 0.50,
            vol: 0.25,
            expected: 12.7857,
            tolerance: 1.0e-4,
        },
        EuropeanCase {
            option_type: OptionType::Call,
            strike: 100.00,
            spot: 90.00,
            dividend: 0.10,
            rate: 0.10,
            expiry: 0.50,
            vol: 0.35,
            expected: 4.9329,
            tolerance: 1.0e-4,
        },
        EuropeanCase {
            option_type: OptionType::Call,
            strike: 100.00,
            spot: 100.00,
            dividend: 0.10,
            rate: 0.10,
            expiry: 0.50,
            vol: 0.35,
            expected: 9.3679,
            tolerance: 1.0e-4,
        },
        EuropeanCase {
            option_type: OptionType::Call,
            strike: 100.00,
            spot: 110.00,
            dividend: 0.10,
            rate: 0.10,
            expiry: 0.50,
            vol: 0.35,
            expected: 15.3086,
            tolerance: 1.0e-4,
        },
        // pag 24 — Puts
        EuropeanCase {
            option_type: OptionType::Put,
            strike: 100.00,
            spot: 90.00,
            dividend: 0.10,
            rate: 0.10,
            expiry: 0.10,
            vol: 0.15,
            expected: 9.9210,
            tolerance: 1.0e-4,
        },
        EuropeanCase {
            option_type: OptionType::Put,
            strike: 100.00,
            spot: 100.00,
            dividend: 0.10,
            rate: 0.10,
            expiry: 0.10,
            vol: 0.15,
            expected: 1.8734,
            tolerance: 1.0e-4,
        },
        EuropeanCase {
            option_type: OptionType::Put,
            strike: 100.00,
            spot: 110.00,
            dividend: 0.10,
            rate: 0.10,
            expiry: 0.10,
            vol: 0.15,
            expected: 0.0408,
            tolerance: 1.0e-4,
        },
        EuropeanCase {
            option_type: OptionType::Put,
            strike: 100.00,
            spot: 90.00,
            dividend: 0.10,
            rate: 0.10,
            expiry: 0.10,
            vol: 0.25,
            expected: 10.2155,
            tolerance: 1.0e-4,
        },
        EuropeanCase {
            option_type: OptionType::Put,
            strike: 100.00,
            spot: 100.00,
            dividend: 0.10,
            rate: 0.10,
            expiry: 0.10,
            vol: 0.25,
            expected: 3.1217,
            tolerance: 1.0e-4,
        },
        EuropeanCase {
            option_type: OptionType::Put,
            strike: 100.00,
            spot: 110.00,
            dividend: 0.10,
            rate: 0.10,
            expiry: 0.10,
            vol: 0.25,
            expected: 0.4551,
            tolerance: 1.0e-4,
        },
        EuropeanCase {
            option_type: OptionType::Put,
            strike: 100.00,
            spot: 90.00,
            dividend: 0.10,
            rate: 0.10,
            expiry: 0.10,
            vol: 0.35,
            expected: 10.8479,
            tolerance: 1.0e-4,
        },
        EuropeanCase {
            option_type: OptionType::Put,
            strike: 100.00,
            spot: 100.00,
            dividend: 0.10,
            rate: 0.10,
            expiry: 0.10,
            vol: 0.35,
            expected: 4.3693,
            tolerance: 1.0e-4,
        },
        EuropeanCase {
            option_type: OptionType::Put,
            strike: 100.00,
            spot: 110.00,
            dividend: 0.10,
            rate: 0.10,
            expiry: 0.10,
            vol: 0.35,
            expected: 1.2376,
            tolerance: 1.0e-4,
        },
        EuropeanCase {
            option_type: OptionType::Put,
            strike: 100.00,
            spot: 90.00,
            dividend: 0.10,
            rate: 0.10,
            expiry: 0.50,
            vol: 0.15,
            expected: 10.3192,
            tolerance: 1.0e-4,
        },
        EuropeanCase {
            option_type: OptionType::Put,
            strike: 100.00,
            spot: 100.00,
            dividend: 0.10,
            rate: 0.10,
            expiry: 0.50,
            vol: 0.15,
            expected: 4.0232,
            tolerance: 1.0e-4,
        },
        EuropeanCase {
            option_type: OptionType::Put,
            strike: 100.00,
            spot: 110.00,
            dividend: 0.10,
            rate: 0.10,
            expiry: 0.50,
            vol: 0.15,
            expected: 1.0646,
            tolerance: 1.0e-4,
        },
        EuropeanCase {
            option_type: OptionType::Put,
            strike: 100.00,
            spot: 90.00,
            dividend: 0.10,
            rate: 0.10,
            expiry: 0.50,
            vol: 0.25,
            expected: 12.2149,
            tolerance: 1.0e-4,
        },
        EuropeanCase {
            option_type: OptionType::Put,
            strike: 100.00,
            spot: 100.00,
            dividend: 0.10,
            rate: 0.10,
            expiry: 0.50,
            vol: 0.25,
            expected: 6.6997,
            tolerance: 1.0e-4,
        },
        EuropeanCase {
            option_type: OptionType::Put,
            strike: 100.00,
            spot: 110.00,
            dividend: 0.10,
            rate: 0.10,
            expiry: 0.50,
            vol: 0.25,
            expected: 3.2734,
            tolerance: 1.0e-4,
        },
        EuropeanCase {
            option_type: OptionType::Put,
            strike: 100.00,
            spot: 90.00,
            dividend: 0.10,
            rate: 0.10,
            expiry: 0.50,
            vol: 0.35,
            expected: 14.4452,
            tolerance: 1.0e-4,
        },
        EuropeanCase {
            option_type: OptionType::Put,
            strike: 100.00,
            spot: 100.00,
            dividend: 0.10,
            rate: 0.10,
            expiry: 0.50,
            vol: 0.35,
            expected: 9.3679,
            tolerance: 1.0e-4,
        },
        EuropeanCase {
            option_type: OptionType::Put,
            strike: 100.00,
            spot: 110.00,
            dividend: 0.10,
            rate: 0.10,
            expiry: 0.50,
            vol: 0.35,
            expected: 5.7963,
            tolerance: 1.0e-4,
        },
        // pag 27
        EuropeanCase {
            option_type: OptionType::Call,
            strike: 40.00,
            spot: 42.00,
            dividend: 0.08,
            rate: 0.04,
            expiry: 0.75,
            vol: 0.35,
            expected: 5.0975,
            tolerance: 1.0e-4,
        },
    ]
}

// ============================================================================
// Barrier options — European exercise only
// Source: QuantLib test-suite/barrieroption.cpp lines 333-460
// Reference: Haug, "Option Pricing Formulas", McGraw-Hill 1998, pag. 72
// ============================================================================

struct BarrierCase {
    direction: BarrierDirection,
    style: BarrierStyle,
    barrier: f64,
    rebate: f64,
    option_type: OptionType,
    strike: f64,
    spot: f64,
    dividend: f64,
    rate: f64,
    expiry: f64,
    vol: f64,
    expected: f64,
    tolerance: f64,
}

fn barrier_haug_cases() -> Vec<BarrierCase> {
    vec![
        // vol=0.25 — Calls
        BarrierCase {
            direction: BarrierDirection::Down,
            style: BarrierStyle::Out,
            barrier: 95.0,
            rebate: 3.0,
            option_type: OptionType::Call,
            strike: 90.0,
            spot: 100.0,
            dividend: 0.04,
            rate: 0.08,
            expiry: 0.50,
            vol: 0.25,
            expected: 9.0246,
            tolerance: 1.0e-4,
        },
        BarrierCase {
            direction: BarrierDirection::Down,
            style: BarrierStyle::Out,
            barrier: 95.0,
            rebate: 3.0,
            option_type: OptionType::Call,
            strike: 100.0,
            spot: 100.0,
            dividend: 0.04,
            rate: 0.08,
            expiry: 0.50,
            vol: 0.25,
            expected: 6.7924,
            tolerance: 1.0e-4,
        },
        BarrierCase {
            direction: BarrierDirection::Down,
            style: BarrierStyle::Out,
            barrier: 95.0,
            rebate: 3.0,
            option_type: OptionType::Call,
            strike: 110.0,
            spot: 100.0,
            dividend: 0.04,
            rate: 0.08,
            expiry: 0.50,
            vol: 0.25,
            expected: 4.8759,
            tolerance: 1.0e-4,
        },
        BarrierCase {
            direction: BarrierDirection::Down,
            style: BarrierStyle::Out,
            barrier: 100.0,
            rebate: 3.0,
            option_type: OptionType::Call,
            strike: 90.0,
            spot: 100.0,
            dividend: 0.04,
            rate: 0.08,
            expiry: 0.50,
            vol: 0.25,
            expected: 3.0000,
            tolerance: 1.0e-4,
        },
        BarrierCase {
            direction: BarrierDirection::Down,
            style: BarrierStyle::Out,
            barrier: 100.0,
            rebate: 3.0,
            option_type: OptionType::Call,
            strike: 100.0,
            spot: 100.0,
            dividend: 0.04,
            rate: 0.08,
            expiry: 0.50,
            vol: 0.25,
            expected: 3.0000,
            tolerance: 1.0e-4,
        },
        BarrierCase {
            direction: BarrierDirection::Down,
            style: BarrierStyle::Out,
            barrier: 100.0,
            rebate: 3.0,
            option_type: OptionType::Call,
            strike: 110.0,
            spot: 100.0,
            dividend: 0.04,
            rate: 0.08,
            expiry: 0.50,
            vol: 0.25,
            expected: 3.0000,
            tolerance: 1.0e-4,
        },
        BarrierCase {
            direction: BarrierDirection::Up,
            style: BarrierStyle::Out,
            barrier: 105.0,
            rebate: 3.0,
            option_type: OptionType::Call,
            strike: 90.0,
            spot: 100.0,
            dividend: 0.04,
            rate: 0.08,
            expiry: 0.50,
            vol: 0.25,
            expected: 2.6789,
            tolerance: 1.0e-4,
        },
        BarrierCase {
            direction: BarrierDirection::Up,
            style: BarrierStyle::Out,
            barrier: 105.0,
            rebate: 3.0,
            option_type: OptionType::Call,
            strike: 100.0,
            spot: 100.0,
            dividend: 0.04,
            rate: 0.08,
            expiry: 0.50,
            vol: 0.25,
            expected: 2.3580,
            tolerance: 1.0e-4,
        },
        BarrierCase {
            direction: BarrierDirection::Up,
            style: BarrierStyle::Out,
            barrier: 105.0,
            rebate: 3.0,
            option_type: OptionType::Call,
            strike: 110.0,
            spot: 100.0,
            dividend: 0.04,
            rate: 0.08,
            expiry: 0.50,
            vol: 0.25,
            expected: 2.3453,
            tolerance: 1.0e-4,
        },
        BarrierCase {
            direction: BarrierDirection::Down,
            style: BarrierStyle::In,
            barrier: 95.0,
            rebate: 3.0,
            option_type: OptionType::Call,
            strike: 90.0,
            spot: 100.0,
            dividend: 0.04,
            rate: 0.08,
            expiry: 0.50,
            vol: 0.25,
            expected: 7.7627,
            tolerance: 1.0e-4,
        },
        BarrierCase {
            direction: BarrierDirection::Down,
            style: BarrierStyle::In,
            barrier: 95.0,
            rebate: 3.0,
            option_type: OptionType::Call,
            strike: 100.0,
            spot: 100.0,
            dividend: 0.04,
            rate: 0.08,
            expiry: 0.50,
            vol: 0.25,
            expected: 4.0109,
            tolerance: 1.0e-4,
        },
        BarrierCase {
            direction: BarrierDirection::Down,
            style: BarrierStyle::In,
            barrier: 95.0,
            rebate: 3.0,
            option_type: OptionType::Call,
            strike: 110.0,
            spot: 100.0,
            dividend: 0.04,
            rate: 0.08,
            expiry: 0.50,
            vol: 0.25,
            expected: 2.0576,
            tolerance: 1.0e-4,
        },
        BarrierCase {
            direction: BarrierDirection::Down,
            style: BarrierStyle::In,
            barrier: 100.0,
            rebate: 3.0,
            option_type: OptionType::Call,
            strike: 90.0,
            spot: 100.0,
            dividend: 0.04,
            rate: 0.08,
            expiry: 0.50,
            vol: 0.25,
            expected: 13.8333,
            tolerance: 1.0e-4,
        },
        BarrierCase {
            direction: BarrierDirection::Down,
            style: BarrierStyle::In,
            barrier: 100.0,
            rebate: 3.0,
            option_type: OptionType::Call,
            strike: 100.0,
            spot: 100.0,
            dividend: 0.04,
            rate: 0.08,
            expiry: 0.50,
            vol: 0.25,
            expected: 7.8494,
            tolerance: 1.0e-4,
        },
        BarrierCase {
            direction: BarrierDirection::Down,
            style: BarrierStyle::In,
            barrier: 100.0,
            rebate: 3.0,
            option_type: OptionType::Call,
            strike: 110.0,
            spot: 100.0,
            dividend: 0.04,
            rate: 0.08,
            expiry: 0.50,
            vol: 0.25,
            expected: 3.9795,
            tolerance: 1.0e-4,
        },
        BarrierCase {
            direction: BarrierDirection::Up,
            style: BarrierStyle::In,
            barrier: 105.0,
            rebate: 3.0,
            option_type: OptionType::Call,
            strike: 90.0,
            spot: 100.0,
            dividend: 0.04,
            rate: 0.08,
            expiry: 0.50,
            vol: 0.25,
            expected: 14.1112,
            tolerance: 1.0e-4,
        },
        BarrierCase {
            direction: BarrierDirection::Up,
            style: BarrierStyle::In,
            barrier: 105.0,
            rebate: 3.0,
            option_type: OptionType::Call,
            strike: 100.0,
            spot: 100.0,
            dividend: 0.04,
            rate: 0.08,
            expiry: 0.50,
            vol: 0.25,
            expected: 8.4482,
            tolerance: 1.0e-4,
        },
        BarrierCase {
            direction: BarrierDirection::Up,
            style: BarrierStyle::In,
            barrier: 105.0,
            rebate: 3.0,
            option_type: OptionType::Call,
            strike: 110.0,
            spot: 100.0,
            dividend: 0.04,
            rate: 0.08,
            expiry: 0.50,
            vol: 0.25,
            expected: 4.5910,
            tolerance: 1.0e-4,
        },
        // vol=0.30 — Calls
        BarrierCase {
            direction: BarrierDirection::Down,
            style: BarrierStyle::Out,
            barrier: 95.0,
            rebate: 3.0,
            option_type: OptionType::Call,
            strike: 90.0,
            spot: 100.0,
            dividend: 0.04,
            rate: 0.08,
            expiry: 0.50,
            vol: 0.30,
            expected: 8.8334,
            tolerance: 1.0e-4,
        },
        BarrierCase {
            direction: BarrierDirection::Down,
            style: BarrierStyle::Out,
            barrier: 95.0,
            rebate: 3.0,
            option_type: OptionType::Call,
            strike: 100.0,
            spot: 100.0,
            dividend: 0.04,
            rate: 0.08,
            expiry: 0.50,
            vol: 0.30,
            expected: 7.0285,
            tolerance: 1.0e-4,
        },
        BarrierCase {
            direction: BarrierDirection::Down,
            style: BarrierStyle::Out,
            barrier: 95.0,
            rebate: 3.0,
            option_type: OptionType::Call,
            strike: 110.0,
            spot: 100.0,
            dividend: 0.04,
            rate: 0.08,
            expiry: 0.50,
            vol: 0.30,
            expected: 5.4137,
            tolerance: 1.0e-4,
        },
        BarrierCase {
            direction: BarrierDirection::Down,
            style: BarrierStyle::Out,
            barrier: 100.0,
            rebate: 3.0,
            option_type: OptionType::Call,
            strike: 90.0,
            spot: 100.0,
            dividend: 0.04,
            rate: 0.08,
            expiry: 0.50,
            vol: 0.30,
            expected: 3.0000,
            tolerance: 1.0e-4,
        },
        BarrierCase {
            direction: BarrierDirection::Down,
            style: BarrierStyle::Out,
            barrier: 100.0,
            rebate: 3.0,
            option_type: OptionType::Call,
            strike: 100.0,
            spot: 100.0,
            dividend: 0.04,
            rate: 0.08,
            expiry: 0.50,
            vol: 0.30,
            expected: 3.0000,
            tolerance: 1.0e-4,
        },
        BarrierCase {
            direction: BarrierDirection::Down,
            style: BarrierStyle::Out,
            barrier: 100.0,
            rebate: 3.0,
            option_type: OptionType::Call,
            strike: 110.0,
            spot: 100.0,
            dividend: 0.04,
            rate: 0.08,
            expiry: 0.50,
            vol: 0.30,
            expected: 3.0000,
            tolerance: 1.0e-4,
        },
        BarrierCase {
            direction: BarrierDirection::Up,
            style: BarrierStyle::Out,
            barrier: 105.0,
            rebate: 3.0,
            option_type: OptionType::Call,
            strike: 90.0,
            spot: 100.0,
            dividend: 0.04,
            rate: 0.08,
            expiry: 0.50,
            vol: 0.30,
            expected: 2.6341,
            tolerance: 1.0e-4,
        },
        BarrierCase {
            direction: BarrierDirection::Up,
            style: BarrierStyle::Out,
            barrier: 105.0,
            rebate: 3.0,
            option_type: OptionType::Call,
            strike: 100.0,
            spot: 100.0,
            dividend: 0.04,
            rate: 0.08,
            expiry: 0.50,
            vol: 0.30,
            expected: 2.4389,
            tolerance: 1.0e-4,
        },
        BarrierCase {
            direction: BarrierDirection::Up,
            style: BarrierStyle::Out,
            barrier: 105.0,
            rebate: 3.0,
            option_type: OptionType::Call,
            strike: 110.0,
            spot: 100.0,
            dividend: 0.04,
            rate: 0.08,
            expiry: 0.50,
            vol: 0.30,
            expected: 2.4315,
            tolerance: 1.0e-4,
        },
        BarrierCase {
            direction: BarrierDirection::Down,
            style: BarrierStyle::In,
            barrier: 95.0,
            rebate: 3.0,
            option_type: OptionType::Call,
            strike: 90.0,
            spot: 100.0,
            dividend: 0.04,
            rate: 0.08,
            expiry: 0.50,
            vol: 0.30,
            expected: 9.0093,
            tolerance: 1.0e-4,
        },
        BarrierCase {
            direction: BarrierDirection::Down,
            style: BarrierStyle::In,
            barrier: 95.0,
            rebate: 3.0,
            option_type: OptionType::Call,
            strike: 100.0,
            spot: 100.0,
            dividend: 0.04,
            rate: 0.08,
            expiry: 0.50,
            vol: 0.30,
            expected: 5.1370,
            tolerance: 1.0e-4,
        },
        BarrierCase {
            direction: BarrierDirection::Down,
            style: BarrierStyle::In,
            barrier: 95.0,
            rebate: 3.0,
            option_type: OptionType::Call,
            strike: 110.0,
            spot: 100.0,
            dividend: 0.04,
            rate: 0.08,
            expiry: 0.50,
            vol: 0.30,
            expected: 2.8517,
            tolerance: 1.0e-4,
        },
        BarrierCase {
            direction: BarrierDirection::Down,
            style: BarrierStyle::In,
            barrier: 100.0,
            rebate: 3.0,
            option_type: OptionType::Call,
            strike: 90.0,
            spot: 100.0,
            dividend: 0.04,
            rate: 0.08,
            expiry: 0.50,
            vol: 0.30,
            expected: 14.8816,
            tolerance: 1.0e-4,
        },
        BarrierCase {
            direction: BarrierDirection::Down,
            style: BarrierStyle::In,
            barrier: 100.0,
            rebate: 3.0,
            option_type: OptionType::Call,
            strike: 100.0,
            spot: 100.0,
            dividend: 0.04,
            rate: 0.08,
            expiry: 0.50,
            vol: 0.30,
            expected: 9.2045,
            tolerance: 1.0e-4,
        },
        BarrierCase {
            direction: BarrierDirection::Down,
            style: BarrierStyle::In,
            barrier: 100.0,
            rebate: 3.0,
            option_type: OptionType::Call,
            strike: 110.0,
            spot: 100.0,
            dividend: 0.04,
            rate: 0.08,
            expiry: 0.50,
            vol: 0.30,
            expected: 5.3043,
            tolerance: 1.0e-4,
        },
        BarrierCase {
            direction: BarrierDirection::Up,
            style: BarrierStyle::In,
            barrier: 105.0,
            rebate: 3.0,
            option_type: OptionType::Call,
            strike: 90.0,
            spot: 100.0,
            dividend: 0.04,
            rate: 0.08,
            expiry: 0.50,
            vol: 0.30,
            expected: 15.2098,
            tolerance: 1.0e-4,
        },
        BarrierCase {
            direction: BarrierDirection::Up,
            style: BarrierStyle::In,
            barrier: 105.0,
            rebate: 3.0,
            option_type: OptionType::Call,
            strike: 100.0,
            spot: 100.0,
            dividend: 0.04,
            rate: 0.08,
            expiry: 0.50,
            vol: 0.30,
            expected: 9.7278,
            tolerance: 1.0e-4,
        },
        BarrierCase {
            direction: BarrierDirection::Up,
            style: BarrierStyle::In,
            barrier: 105.0,
            rebate: 3.0,
            option_type: OptionType::Call,
            strike: 110.0,
            spot: 100.0,
            dividend: 0.04,
            rate: 0.08,
            expiry: 0.50,
            vol: 0.30,
            expected: 5.8350,
            tolerance: 1.0e-4,
        },
        // vol=0.25 — Puts
        BarrierCase {
            direction: BarrierDirection::Down,
            style: BarrierStyle::Out,
            barrier: 95.0,
            rebate: 3.0,
            option_type: OptionType::Put,
            strike: 90.0,
            spot: 100.0,
            dividend: 0.04,
            rate: 0.08,
            expiry: 0.50,
            vol: 0.25,
            expected: 2.2798,
            tolerance: 1.0e-4,
        },
        BarrierCase {
            direction: BarrierDirection::Down,
            style: BarrierStyle::Out,
            barrier: 95.0,
            rebate: 3.0,
            option_type: OptionType::Put,
            strike: 100.0,
            spot: 100.0,
            dividend: 0.04,
            rate: 0.08,
            expiry: 0.50,
            vol: 0.25,
            expected: 2.2947,
            tolerance: 1.0e-4,
        },
        BarrierCase {
            direction: BarrierDirection::Down,
            style: BarrierStyle::Out,
            barrier: 95.0,
            rebate: 3.0,
            option_type: OptionType::Put,
            strike: 110.0,
            spot: 100.0,
            dividend: 0.04,
            rate: 0.08,
            expiry: 0.50,
            vol: 0.25,
            expected: 2.6252,
            tolerance: 1.0e-4,
        },
        BarrierCase {
            direction: BarrierDirection::Down,
            style: BarrierStyle::Out,
            barrier: 100.0,
            rebate: 3.0,
            option_type: OptionType::Put,
            strike: 90.0,
            spot: 100.0,
            dividend: 0.04,
            rate: 0.08,
            expiry: 0.50,
            vol: 0.25,
            expected: 3.0000,
            tolerance: 1.0e-4,
        },
        BarrierCase {
            direction: BarrierDirection::Down,
            style: BarrierStyle::Out,
            barrier: 100.0,
            rebate: 3.0,
            option_type: OptionType::Put,
            strike: 100.0,
            spot: 100.0,
            dividend: 0.04,
            rate: 0.08,
            expiry: 0.50,
            vol: 0.25,
            expected: 3.0000,
            tolerance: 1.0e-4,
        },
        BarrierCase {
            direction: BarrierDirection::Down,
            style: BarrierStyle::Out,
            barrier: 100.0,
            rebate: 3.0,
            option_type: OptionType::Put,
            strike: 110.0,
            spot: 100.0,
            dividend: 0.04,
            rate: 0.08,
            expiry: 0.50,
            vol: 0.25,
            expected: 3.0000,
            tolerance: 1.0e-4,
        },
        BarrierCase {
            direction: BarrierDirection::Up,
            style: BarrierStyle::Out,
            barrier: 105.0,
            rebate: 3.0,
            option_type: OptionType::Put,
            strike: 90.0,
            spot: 100.0,
            dividend: 0.04,
            rate: 0.08,
            expiry: 0.50,
            vol: 0.25,
            expected: 3.7760,
            tolerance: 1.0e-4,
        },
        BarrierCase {
            direction: BarrierDirection::Up,
            style: BarrierStyle::Out,
            barrier: 105.0,
            rebate: 3.0,
            option_type: OptionType::Put,
            strike: 100.0,
            spot: 100.0,
            dividend: 0.04,
            rate: 0.08,
            expiry: 0.50,
            vol: 0.25,
            expected: 5.4932,
            tolerance: 1.0e-4,
        },
        BarrierCase {
            direction: BarrierDirection::Up,
            style: BarrierStyle::Out,
            barrier: 105.0,
            rebate: 3.0,
            option_type: OptionType::Put,
            strike: 110.0,
            spot: 100.0,
            dividend: 0.04,
            rate: 0.08,
            expiry: 0.50,
            vol: 0.25,
            expected: 7.5187,
            tolerance: 1.0e-4,
        },
        BarrierCase {
            direction: BarrierDirection::Down,
            style: BarrierStyle::In,
            barrier: 95.0,
            rebate: 3.0,
            option_type: OptionType::Put,
            strike: 90.0,
            spot: 100.0,
            dividend: 0.04,
            rate: 0.08,
            expiry: 0.50,
            vol: 0.25,
            expected: 2.9586,
            tolerance: 1.0e-4,
        },
        BarrierCase {
            direction: BarrierDirection::Down,
            style: BarrierStyle::In,
            barrier: 95.0,
            rebate: 3.0,
            option_type: OptionType::Put,
            strike: 100.0,
            spot: 100.0,
            dividend: 0.04,
            rate: 0.08,
            expiry: 0.50,
            vol: 0.25,
            expected: 6.5677,
            tolerance: 1.0e-4,
        },
        BarrierCase {
            direction: BarrierDirection::Down,
            style: BarrierStyle::In,
            barrier: 95.0,
            rebate: 3.0,
            option_type: OptionType::Put,
            strike: 110.0,
            spot: 100.0,
            dividend: 0.04,
            rate: 0.08,
            expiry: 0.50,
            vol: 0.25,
            expected: 11.9752,
            tolerance: 1.0e-4,
        },
        BarrierCase {
            direction: BarrierDirection::Down,
            style: BarrierStyle::In,
            barrier: 100.0,
            rebate: 3.0,
            option_type: OptionType::Put,
            strike: 90.0,
            spot: 100.0,
            dividend: 0.04,
            rate: 0.08,
            expiry: 0.50,
            vol: 0.25,
            expected: 2.2845,
            tolerance: 1.0e-4,
        },
        BarrierCase {
            direction: BarrierDirection::Down,
            style: BarrierStyle::In,
            barrier: 100.0,
            rebate: 3.0,
            option_type: OptionType::Put,
            strike: 100.0,
            spot: 100.0,
            dividend: 0.04,
            rate: 0.08,
            expiry: 0.50,
            vol: 0.25,
            expected: 5.9085,
            tolerance: 1.0e-4,
        },
        BarrierCase {
            direction: BarrierDirection::Down,
            style: BarrierStyle::In,
            barrier: 100.0,
            rebate: 3.0,
            option_type: OptionType::Put,
            strike: 110.0,
            spot: 100.0,
            dividend: 0.04,
            rate: 0.08,
            expiry: 0.50,
            vol: 0.25,
            expected: 11.6465,
            tolerance: 1.0e-4,
        },
        BarrierCase {
            direction: BarrierDirection::Up,
            style: BarrierStyle::In,
            barrier: 105.0,
            rebate: 3.0,
            option_type: OptionType::Put,
            strike: 90.0,
            spot: 100.0,
            dividend: 0.04,
            rate: 0.08,
            expiry: 0.50,
            vol: 0.25,
            expected: 1.4653,
            tolerance: 1.0e-4,
        },
        BarrierCase {
            direction: BarrierDirection::Up,
            style: BarrierStyle::In,
            barrier: 105.0,
            rebate: 3.0,
            option_type: OptionType::Put,
            strike: 100.0,
            spot: 100.0,
            dividend: 0.04,
            rate: 0.08,
            expiry: 0.50,
            vol: 0.25,
            expected: 3.3721,
            tolerance: 1.0e-4,
        },
        BarrierCase {
            direction: BarrierDirection::Up,
            style: BarrierStyle::In,
            barrier: 105.0,
            rebate: 3.0,
            option_type: OptionType::Put,
            strike: 110.0,
            spot: 100.0,
            dividend: 0.04,
            rate: 0.08,
            expiry: 0.50,
            vol: 0.25,
            expected: 7.0846,
            tolerance: 1.0e-4,
        },
        // vol=0.30 — Puts
        BarrierCase {
            direction: BarrierDirection::Down,
            style: BarrierStyle::Out,
            barrier: 95.0,
            rebate: 3.0,
            option_type: OptionType::Put,
            strike: 90.0,
            spot: 100.0,
            dividend: 0.04,
            rate: 0.08,
            expiry: 0.50,
            vol: 0.30,
            expected: 2.4170,
            tolerance: 1.0e-4,
        },
        BarrierCase {
            direction: BarrierDirection::Down,
            style: BarrierStyle::Out,
            barrier: 95.0,
            rebate: 3.0,
            option_type: OptionType::Put,
            strike: 100.0,
            spot: 100.0,
            dividend: 0.04,
            rate: 0.08,
            expiry: 0.50,
            vol: 0.30,
            expected: 2.4258,
            tolerance: 1.0e-4,
        },
        BarrierCase {
            direction: BarrierDirection::Down,
            style: BarrierStyle::Out,
            barrier: 95.0,
            rebate: 3.0,
            option_type: OptionType::Put,
            strike: 110.0,
            spot: 100.0,
            dividend: 0.04,
            rate: 0.08,
            expiry: 0.50,
            vol: 0.30,
            expected: 2.6246,
            tolerance: 1.0e-4,
        },
        BarrierCase {
            direction: BarrierDirection::Down,
            style: BarrierStyle::Out,
            barrier: 100.0,
            rebate: 3.0,
            option_type: OptionType::Put,
            strike: 90.0,
            spot: 100.0,
            dividend: 0.04,
            rate: 0.08,
            expiry: 0.50,
            vol: 0.30,
            expected: 3.0000,
            tolerance: 1.0e-4,
        },
        BarrierCase {
            direction: BarrierDirection::Down,
            style: BarrierStyle::Out,
            barrier: 100.0,
            rebate: 3.0,
            option_type: OptionType::Put,
            strike: 100.0,
            spot: 100.0,
            dividend: 0.04,
            rate: 0.08,
            expiry: 0.50,
            vol: 0.30,
            expected: 3.0000,
            tolerance: 1.0e-4,
        },
        BarrierCase {
            direction: BarrierDirection::Down,
            style: BarrierStyle::Out,
            barrier: 100.0,
            rebate: 3.0,
            option_type: OptionType::Put,
            strike: 110.0,
            spot: 100.0,
            dividend: 0.04,
            rate: 0.08,
            expiry: 0.50,
            vol: 0.30,
            expected: 3.0000,
            tolerance: 1.0e-4,
        },
        BarrierCase {
            direction: BarrierDirection::Up,
            style: BarrierStyle::Out,
            barrier: 105.0,
            rebate: 3.0,
            option_type: OptionType::Put,
            strike: 90.0,
            spot: 100.0,
            dividend: 0.04,
            rate: 0.08,
            expiry: 0.50,
            vol: 0.30,
            expected: 4.2293,
            tolerance: 1.0e-4,
        },
        BarrierCase {
            direction: BarrierDirection::Up,
            style: BarrierStyle::Out,
            barrier: 105.0,
            rebate: 3.0,
            option_type: OptionType::Put,
            strike: 100.0,
            spot: 100.0,
            dividend: 0.04,
            rate: 0.08,
            expiry: 0.50,
            vol: 0.30,
            expected: 5.8032,
            tolerance: 1.0e-4,
        },
        BarrierCase {
            direction: BarrierDirection::Up,
            style: BarrierStyle::Out,
            barrier: 105.0,
            rebate: 3.0,
            option_type: OptionType::Put,
            strike: 110.0,
            spot: 100.0,
            dividend: 0.04,
            rate: 0.08,
            expiry: 0.50,
            vol: 0.30,
            expected: 7.5649,
            tolerance: 1.0e-4,
        },
        BarrierCase {
            direction: BarrierDirection::Down,
            style: BarrierStyle::In,
            barrier: 95.0,
            rebate: 3.0,
            option_type: OptionType::Put,
            strike: 90.0,
            spot: 100.0,
            dividend: 0.04,
            rate: 0.08,
            expiry: 0.50,
            vol: 0.30,
            expected: 3.8769,
            tolerance: 1.0e-4,
        },
        BarrierCase {
            direction: BarrierDirection::Down,
            style: BarrierStyle::In,
            barrier: 95.0,
            rebate: 3.0,
            option_type: OptionType::Put,
            strike: 100.0,
            spot: 100.0,
            dividend: 0.04,
            rate: 0.08,
            expiry: 0.50,
            vol: 0.30,
            expected: 7.7989,
            tolerance: 1.0e-4,
        },
        BarrierCase {
            direction: BarrierDirection::Down,
            style: BarrierStyle::In,
            barrier: 95.0,
            rebate: 3.0,
            option_type: OptionType::Put,
            strike: 110.0,
            spot: 100.0,
            dividend: 0.04,
            rate: 0.08,
            expiry: 0.50,
            vol: 0.30,
            expected: 13.3078,
            tolerance: 1.0e-4,
        },
        BarrierCase {
            direction: BarrierDirection::Down,
            style: BarrierStyle::In,
            barrier: 100.0,
            rebate: 3.0,
            option_type: OptionType::Put,
            strike: 90.0,
            spot: 100.0,
            dividend: 0.04,
            rate: 0.08,
            expiry: 0.50,
            vol: 0.30,
            expected: 3.3328,
            tolerance: 1.0e-4,
        },
        BarrierCase {
            direction: BarrierDirection::Down,
            style: BarrierStyle::In,
            barrier: 100.0,
            rebate: 3.0,
            option_type: OptionType::Put,
            strike: 100.0,
            spot: 100.0,
            dividend: 0.04,
            rate: 0.08,
            expiry: 0.50,
            vol: 0.30,
            expected: 7.2636,
            tolerance: 1.0e-4,
        },
        BarrierCase {
            direction: BarrierDirection::Down,
            style: BarrierStyle::In,
            barrier: 100.0,
            rebate: 3.0,
            option_type: OptionType::Put,
            strike: 110.0,
            spot: 100.0,
            dividend: 0.04,
            rate: 0.08,
            expiry: 0.50,
            vol: 0.30,
            expected: 12.9713,
            tolerance: 1.0e-4,
        },
        BarrierCase {
            direction: BarrierDirection::Up,
            style: BarrierStyle::In,
            barrier: 105.0,
            rebate: 3.0,
            option_type: OptionType::Put,
            strike: 90.0,
            spot: 100.0,
            dividend: 0.04,
            rate: 0.08,
            expiry: 0.50,
            vol: 0.30,
            expected: 2.0658,
            tolerance: 1.0e-4,
        },
        BarrierCase {
            direction: BarrierDirection::Up,
            style: BarrierStyle::In,
            barrier: 105.0,
            rebate: 3.0,
            option_type: OptionType::Put,
            strike: 100.0,
            spot: 100.0,
            dividend: 0.04,
            rate: 0.08,
            expiry: 0.50,
            vol: 0.30,
            expected: 4.4226,
            tolerance: 1.0e-4,
        },
        BarrierCase {
            direction: BarrierDirection::Up,
            style: BarrierStyle::In,
            barrier: 105.0,
            rebate: 3.0,
            option_type: OptionType::Put,
            strike: 110.0,
            spot: 100.0,
            dividend: 0.04,
            rate: 0.08,
            expiry: 0.50,
            vol: 0.30,
            expected: 8.3686,
            tolerance: 1.0e-4,
        },
    ]
}

// ============================================================================
// Heston model — Alan Lewis reference prices
// Source: QuantLib test-suite/hestonmodel.cpp lines 1288-1415
// Reference: Alan Lewis, posted on wilmott.com (12-digit precision)
// Parameters: S=100, v0=0.04, rho=-0.5, sigma=1.0, kappa=4.0, theta=0.25,
//             r=0.01, q=0.02, T=1yr
// ============================================================================

struct HestonCase {
    option_type: OptionType,
    strike: f64,
    expected: f64,
}

fn heston_alan_lewis_cases() -> (f64, f64, f64, f64, f64, f64, f64, f64, f64, Vec<HestonCase>) {
    // Common parameters
    let spot = 100.0;
    let v0 = 0.04;
    let rho = -0.5;
    let sigma_v = 1.0;
    let kappa = 4.0;
    let theta = 0.25;
    let r = 0.01;
    let q = 0.02;
    let t = 1.0;

    let cases = vec![
        HestonCase {
            option_type: OptionType::Put,
            strike: 80.0,
            expected: 7.958878113256768,
        },
        HestonCase {
            option_type: OptionType::Call,
            strike: 80.0,
            expected: 26.774758743998854,
        },
        HestonCase {
            option_type: OptionType::Put,
            strike: 90.0,
            expected: 12.017966707346305,
        },
        HestonCase {
            option_type: OptionType::Call,
            strike: 90.0,
            expected: 20.933_349_000_596_71,
        },
        HestonCase {
            option_type: OptionType::Put,
            strike: 100.0,
            expected: 17.055_270_961_270_11,
        },
        HestonCase {
            option_type: OptionType::Call,
            strike: 100.0,
            expected: 16.070154917028834,
        },
        HestonCase {
            option_type: OptionType::Put,
            strike: 110.0,
            expected: 23.017_825_898_442_8,
        },
        HestonCase {
            option_type: OptionType::Call,
            strike: 110.0,
            expected: 12.132211516709845,
        },
        HestonCase {
            option_type: OptionType::Put,
            strike: 120.0,
            expected: 29.811026202682472,
        },
        HestonCase {
            option_type: OptionType::Call,
            strike: 120.0,
            expected: 9.024913483457836,
        },
    ];

    (spot, v0, rho, sigma_v, kappa, theta, r, q, t, cases)
}

// ============================================================================
// Heston model — cached regression values
// Source: QuantLib test-suite/hestonmodel.cpp lines 440-536
// ============================================================================

struct HestonCachedCase {
    option_type: OptionType,
    strike: f64,
    spot: f64,
    rate: f64,
    dividend: f64,
    expiry: f64,
    v0: f64,
    kappa: f64,
    theta: f64,
    sigma_v: f64,
    rho: f64,
    expected: f64,
}

fn heston_cached_cases() -> Vec<HestonCachedCase> {
    vec![
        // Case 1: S=1.0, K=1.05, T≈0.25yr
        HestonCachedCase {
            option_type: OptionType::Call,
            strike: 1.05,
            spot: 1.0,
            rate: 0.0225,
            dividend: 0.02,
            expiry: 0.25,
            v0: 0.1,
            kappa: 3.16,
            theta: 0.09,
            sigma_v: 0.4,
            rho: -0.2,
            expected: 0.0404774515,
        },
        // Case 2: various strikes, T≈0.7yr
        HestonCachedCase {
            option_type: OptionType::Call,
            strike: 0.9,
            spot: 1.0,
            rate: 0.05,
            dividend: 0.02,
            expiry: 0.7,
            v0: 0.09,
            kappa: 1.2,
            theta: 0.08,
            sigma_v: 1.8,
            rho: -0.45,
            expected: 0.1330371,
        },
        HestonCachedCase {
            option_type: OptionType::Call,
            strike: 1.0,
            spot: 1.0,
            rate: 0.05,
            dividend: 0.02,
            expiry: 0.7,
            v0: 0.09,
            kappa: 1.2,
            theta: 0.08,
            sigma_v: 1.8,
            rho: -0.45,
            expected: 0.0641016,
        },
        HestonCachedCase {
            option_type: OptionType::Call,
            strike: 1.1,
            spot: 1.0,
            rate: 0.05,
            dividend: 0.02,
            expiry: 0.7,
            v0: 0.09,
            kappa: 1.2,
            theta: 0.08,
            sigma_v: 1.8,
            rho: -0.45,
            expected: 0.0270645,
        },
    ]
}

#[inline]
#[allow(clippy::too_many_arguments)]
fn heston_fft_option_price(
    option_type: OptionType,
    spot: f64,
    strike: f64,
    rate: f64,
    dividend: f64,
    expiry: f64,
    v0: f64,
    kappa: f64,
    theta: f64,
    sigma_v: f64,
    rho: f64,
) -> f64 {
    let call = heston_price_fft(
        spot,
        &[strike],
        rate,
        dividend,
        v0,
        kappa,
        theta,
        sigma_v,
        rho,
        expiry,
    )[0]
    .1;

    match option_type {
        OptionType::Call => call,
        OptionType::Put => {
            call - spot * (-dividend * expiry).exp() + strike * (-rate * expiry).exp()
        }
    }
}

// ============================================================================
// Tests
// ============================================================================

#[test]
fn test_european_haug_reference_values() {
    // 43 cases from Haug "Option Pricing Formulas" via QuantLib europeanoption.cpp
    let engine = BlackScholesEngine::new();
    let cases = european_haug_cases();

    for (i, c) in cases.iter().enumerate() {
        let option = match c.option_type {
            OptionType::Call => VanillaOption::european_call(c.strike, c.expiry),
            OptionType::Put => VanillaOption::european_put(c.strike, c.expiry),
        };

        let market = Market::builder()
            .spot(c.spot)
            .rate(c.rate)
            .dividend_yield(c.dividend)
            .flat_vol(c.vol)
            .build()
            .unwrap();

        let result = engine.price(&option, &market).unwrap();
        let error = (result.price - c.expected).abs();

        assert!(
            error <= c.tolerance,
            "European case {i}: {:?} S={} K={} q={} r={} t={} vol={} expected={} got={:.6} err={:.2e}",
            c.option_type,
            c.spot,
            c.strike,
            c.dividend,
            c.rate,
            c.expiry,
            c.vol,
            c.expected,
            result.price,
            error
        );
    }

    println!("✓ All {} European Haug reference cases passed", cases.len());
}

#[test]
fn test_barrier_haug_reference_values() {
    // 72 European barrier cases from Haug via QuantLib barrieroption.cpp
    let engine = BarrierAnalyticEngine::new();
    let cases = barrier_haug_cases();

    for (i, c) in cases.iter().enumerate() {
        let mut builder = BarrierOption::builder();

        builder = match c.option_type {
            OptionType::Call => builder.call(),
            OptionType::Put => builder.put(),
        };

        builder = match (c.direction, c.style) {
            (BarrierDirection::Down, BarrierStyle::Out) => builder.down_and_out(c.barrier),
            (BarrierDirection::Up, BarrierStyle::Out) => builder.up_and_out(c.barrier),
            (BarrierDirection::Down, BarrierStyle::In) => builder.down_and_in(c.barrier),
            (BarrierDirection::Up, BarrierStyle::In) => builder.up_and_in(c.barrier),
        };

        let option = builder
            .strike(c.strike)
            .expiry(c.expiry)
            .rebate(c.rebate)
            .build()
            .unwrap();

        let market = Market::builder()
            .spot(c.spot)
            .rate(c.rate)
            .dividend_yield(c.dividend)
            .flat_vol(c.vol)
            .build()
            .unwrap();

        let result = engine.price(&option, &market).unwrap();
        let error = (result.price - c.expected).abs();

        assert!(
            error <= c.tolerance,
            "Barrier case {i}: {:?}/{:?} {:?} S={} K={} B={} R={} expected={} got={:.6} err={:.2e}",
            c.direction,
            c.style,
            c.option_type,
            c.spot,
            c.strike,
            c.barrier,
            c.rebate,
            c.expected,
            result.price,
            error
        );
    }

    println!("✓ All {} Barrier Haug reference cases passed", cases.len());
}

#[test]
fn test_heston_alan_lewis_reference_values() {
    // 10 cases (5 strikes × put+call) from Alan Lewis, wilmott.com
    // via QuantLib hestonmodel.cpp lines 1288-1415
    // Tolerance 1e-2: our FFT engine won't match 12 digits but should be within 1%
    let (spot, v0, rho, sigma_v, kappa, theta, r, q, t, cases) = heston_alan_lewis_cases();
    let tolerance = 1e-2;

    for (i, c) in cases.iter().enumerate() {
        let price = heston_fft_option_price(
            c.option_type,
            spot,
            c.strike,
            r,
            q,
            t,
            v0,
            kappa,
            theta,
            sigma_v,
            rho,
        );
        let error = (price - c.expected).abs();

        assert!(
            error <= tolerance,
            "Heston Lewis case {i}: {:?} K={} expected={:.12} got={:.6} err={:.2e}",
            c.option_type,
            c.strike,
            c.expected,
            price,
            error
        );
    }

    println!(
        "✓ All {} Heston Alan Lewis reference cases passed",
        cases.len()
    );
}

#[test]
fn test_heston_cached_regression_values() {
    // Cached values from QuantLib hestonmodel.cpp lines 440-536
    // Tolerance 2e-2: our FFT-based engine differs from QuantLib's Gauss-Laguerre integration
    let cases = heston_cached_cases();
    let tolerance = 2e-2;

    for (i, c) in cases.iter().enumerate() {
        let price = heston_fft_option_price(
            c.option_type,
            c.spot,
            c.strike,
            c.rate,
            c.dividend,
            c.expiry,
            c.v0,
            c.kappa,
            c.theta,
            c.sigma_v,
            c.rho,
        );
        let error = (price - c.expected).abs();

        assert!(
            error <= tolerance,
            "Heston cached case {i}: S={} K={} expected={:.10} got={:.6} err={:.2e}",
            c.spot,
            c.strike,
            c.expected,
            price,
            error
        );
    }

    println!(
        "✓ All {} Heston cached regression cases passed",
        cases.len()
    );
}
