"""Check the installed Python extension against the committed Rust API manifest.

Optionally compare the manifest with all-feature rustdoc JSON generated by:
cargo +nightly-2026-03-10 rustdoc --locked -p openferric --all-features --lib -- \
    -Z unstable-options --output-format json
"""

import argparse
import importlib
import json
from pathlib import Path


def resolve(path):
    parts = path.split(".")
    value = importlib.import_module(parts[0])
    for name in parts[1:]:
        value = getattr(value, name)
    return value


def check_python(manifest):
    features = resolve("openferric.build_features")()
    failures = []
    for record in manifest["items"]:
        if not features.get(record.get("feature"), True):
            continue
        path = record["python"]
        try:
            value = resolve(path)
            for method in record.get("methods", {}).values():
                if not hasattr(value, method):
                    failures.append(f"{path}.{method}: missing method for {record['rust']}")
            if record.get("field_access") == "serialized":
                assert hasattr(value, "to_dict"), path
            else:
                for field in record.get("fields", []):
                    if not hasattr(value, field):
                        failures.append(f"{path}.{field}: missing field for {record['rust']}")
        except (AttributeError, AssertionError) as error:
            failures.append(f"{record['rust']}: {path}: {error}")
    return failures


def check_rustdoc(manifest, rustdoc):
    expected = {record["rust"]: record for record in manifest["items"]}
    actual = {}
    index = rustdoc["index"]
    failures = []
    for identifier, path in rustdoc["paths"].items():
        item = index.get(identifier)
        if path["crate_id"] or item is None or item["visibility"] != "public" or path["kind"] == "module":
            continue
        name = "::".join(path["path"])
        actual[name] = item
        record = expected.get(name)
        if record is None or record["status"] != "exposed" or path["kind"] not in ("enum", "struct"):
            continue
        definition = item["inner"][path["kind"]]
        kind = definition.get("kind", {})
        field_ids = kind.get("plain", {}).get("fields", []) if isinstance(kind, dict) else []
        fields = {index[str(field)]["name"] for field in field_ids if index[str(field)]["visibility"] == "public"}
        methods = set()
        for implementation_id in definition["impls"]:
            implementation = index[str(implementation_id)]["inner"]["impl"]
            if implementation["trait"] is not None:
                continue
            for method_id in implementation["items"]:
                method = index[str(method_id)]
                if method["visibility"] == "public" and "function" in method["inner"]:
                    methods.add(method["name"])
        for label, current, recorded in (
            ("fields", fields, set(record.get("fields", []))),
            ("methods", methods, set(record.get("methods", {}))),
        ):
            if current != recorded:
                failures.append(f"{name}: {label} changed: added={current - recorded}, removed={recorded - current}")
        if path["kind"] == "enum":
            variants = {index[str(variant)]["name"] for variant in definition["variants"]}
            if variants != set(record.get("variants", [])):
                failures.append(f"{name}: variants changed")
    for missing in sorted(actual.keys() - expected.keys()):
        failures.append(f"Unreviewed Rust export: {missing}")
    for removed in sorted(expected.keys() - actual.keys()):
        failures.append(f"Removed Rust export: {removed}")
    return failures


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--rustdoc", type=Path)
    arguments = parser.parse_args()
    manifest = json.loads((Path(__file__).resolve().parents[1] / "api_manifest.json").read_text())
    failures = check_python(manifest)
    if arguments.rustdoc:
        failures.extend(check_rustdoc(manifest, json.loads(arguments.rustdoc.read_text())))
    if failures:
        raise SystemExit("\n".join(failures))
    print("Python API manifest verified" + (" against Rust exports" if arguments.rustdoc else ""))


if __name__ == "__main__":
    main()
